# Root logger
log4j.rootLogger=INFO, console, appFile, errorFile

# Console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d %-5p %c:%L - %m%n

# Application log
log4j.appender.appFile=org.apache.log4j.RollingFileAppender
log4j.appender.appFile.File=logs/application.log
log4j.appender.appFile.MaxFileSize=5MB
log4j.appender.appFile.MaxBackupIndex=2
log4j.appender.appFile.layout=org.apache.log4j.PatternLayout
log4j.appender.appFile.layout.ConversionPattern=%d %-5p %c:%L - %m%n

# Error log
log4j.appender.errorFile=org.apache.log4j.RollingFileAppender
log4j.appender.errorFile.File=logs/error.log
log4j.appender.errorFile.Threshold=ERROR
log4j.appender.errorFile.MaxFileSize=5MB
log4j.appender.errorFile.MaxBackupIndex=2
log4j.appender.errorFile.layout=org.apache.log4j.PatternLayout
log4j.appender.errorFile.layout.ConversionPattern=%d %-5p %c:%L - %m%n